GET http://localhost:3001/api/notes

###
DELETE http://localhost:3001/api/notes/5

###
POST http://localhost:3001/api/notes
Content-Type: application/json

 {
    "content": "Nota nueva",
    "important": true
 }